global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: flask_poc_app
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']