apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: http-metrics-app
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: http-metrics-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
