apiVersion: v1
kind: Service
metadata:
  name: flask-poc-app
  namespace: devops-poc-application-namespace
  labels:
    app: flask-poc-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: flask-poc-app
