pipeline {
  agent {
    docker {
      image 'python:3.13-alpine'
    }
  }

  environment {
    REPO_URL = 'https://github.com/gabrielSpassos/docker-studies.git'
  }

  stages {
    stage('Clone Repository') {
      steps {
        git url: "${REPO_URL}", branch: 'master'
      }
    }

    stage('Install Dependencies') {
      steps {
        dir('devops-poc/app') {
          sh 'echo "Installing dependencies..."'
          sh 'pip3 install -r requirements.txt'
        }
      }
    }

    stage('Run Tests') {
      steps {
        dir('devops-poc/app') {
          sh 'echo "Running tests..."'
          sh 'pytest test'
          pytest app/test
        }
      }
    }
  }

  post {
    always {
      echo 'Job finished.'
    }
    success {
      echo 'All tests passed ✅'
    }
    failure {
      echo 'Tests failed ❌'
    }
  }
}
