version: "3.9"

services:
  db:
    build: .
    container_name: pgdb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./tests:/tests

volumes:
  db_data:
